openshift/openshift-sdn

README.md, main.go, ovs-simple/controller/controller.go, pkg/registry/registry.go
Do not merge. Needs testing.
@mrunalp review please.
=> Sync mode for running independently of PaaS to register nodes

README.md, main.go, ovs-simple/bin/openshift-sdn-simple-setup-node.sh, ovs-simple/controller/controller.go, pkg/registry/registry.go
=> init minion registry for sync mode, updated README for sync mode

ovs-simple/bin/openshift-sdn-simple-setup-node.sh
=> non-permanence for linux bridge, so that we do not need restart network service

README.md, ovs-simple/bin/openshift-sdn-simple-setup-node.sh
Use `$DOCKER_OPTIONS` env var for docker settings if present
=> Use $DOCKER_OPTIONS env var for docker settings if present

ovs-simple/bin/openshift-sdn-simple-setup-node.sh
=> fix iptables rules for traffic from docker

main.go, ovs-simple/controller/controller.go, pkg/registry/registry.go
=> fix issue#12. Give some slack for etcd to come alive.

main.go
=> Use library function to get hostname.

ovs-simple/controller/controller.go
=> Rename refactor in the controller.

main.go
=> Revert to hostname -f as go builtin doesn't return FQDN.

.travis.yml, hack/test.sh, hack/verify-gofmt.sh
@rajatchopra PTAL. Adding scripts for setting up travis next.
=> Testing infra

main.go
=> remove unnecessary for loop and handle client create error

main.go, ovs-simple/bin/openshift-sdn-simple-setup-node.sh, ovs-simple/controller/controller.go, pkg/netutils/common.go, pkg/registry/registry.go
=> Makes subnets configurable.

main.go, ovs-simple/controller/controller.go
Should catch this error https://github.com/openshift/openshift-sdn/blob/master/main.go#L116-L119
=> Fixed error handling to catch error from newNetworkManager

pkg/netutils/ip_allocator.go, pkg/netutils/ip_allocator_test.go, pkg/netutils/subnet_allocator_test.go
Adds IP allocator, tests and other fixes.
=> Ip allocator

pkg/netutils/ip_allocator_test.go
=> Adds a test for IP release.

Documentation/native/README.md
@rajatchopra PTAL.
I have to add diagram and firewall rules next.
=> WIP: Native docs

Makefile, README.md, hack/build.sh, main.go, openshift-sdn.spec, ovssubnet/bin/openshift-ovs-subnet, ovssubnet/bin/openshift-sdn-kube-subnet-setup.sh, ovssubnet/bin/openshift-sdn-simple-setup-node.sh, ovssubnet/common.go, ovssubnet/controller/doc.go, ovssubnet/controller/kube/kube.go, ovssubnet/controller/lbr/lbr.go
=> Kube integration

ovssubnet/common.go, pkg/api/types.go, pkg/registry/registry.go
@mrunalp Review please.
Minor change to omit revision number in API interface.
=> remove revision arg from api as it is an etcd abstraction

openshift-sdn.spec, ovssubnet/bin/openshift-ovs-subnet
@mrunalp @danwinship
Please review. Tested on the openshift cluster.
=> state file no more with docker 1.6, use ethtool instead. Credit: Dan Winship

ovssubnet/bin/openshift-sdn-kube-subnet-setup.sh
=> Update /etc/sysconfig/docker-network rather than /etc/sysconfig/docker

ovssubnet/bin/openshift-sdn-kube-subnet-setup.sh
=> Add iptables rule to allow forwarding from clusternetwork

ovssubnet/bin/openshift-sdn-kube-subnet-setup.sh, ovssubnet/bin/openshift-sdn-simple-setup-node.sh
=> disable iptables for kube bridges; add forward rules for simple setup

README.md, ovssubnet/bin/openshift-sdn-kube-subnet-setup.sh
PR #75 Reborn
Just fixed the conflicts. Credit @thom311.
=> minor fixes to documentation and openshift-sdn-kube-subnet-setup.sh

main.go, ovssubnet/common.go
Part of openshift/origin#2655
Already included as an UPSTREAM patch
=> Signal when the SDN is ready

ovssubnet/bin/openshift-ovs-subnet
=> ignore the SDN setup/teardown if the NetworkMode of the container is host

ovssubnet/bin/openshift-ovs-subnet
=> fix error in bash script

ovssubnet/controller/multitenant/bin/openshift-ovs-multitenant, ovssubnet/controller/multitenant/bin/openshift-sdn-multitenant-setup.sh
Also, not tested because I'm not sure how to test the services stuff? We need to automate our testing...
=> multitenant cleanups; no actual bug fixes

ovssubnet/controller/kube/bin/openshift-sdn-kube-subnet-setup.sh, ovssubnet/controller/multitenant/bin/openshift-sdn-multitenant-setup.sh
=> Enable IP forwarding during openshift sdn setup

ovssubnet/api/types.go, ovssubnet/common.go, ovssubnet/controller/kube/kube.go, ovssubnet/controller/lbr/lbr.go, ovssubnet/controller/multitenant/bin/openshift-ovs-multitenant, ovssubnet/controller/multitenant/bin/openshift-sdn-multitenant-setup.sh, ovssubnet/controller/multitenant/multitenant.go, ovssubnet/registry/registry.go
Implementation of the basis of service isolation; does not actually implement it; it will only be implemented in origin
=> service isolation support

hack/test.sh, pkg/netutils/server/server_test.go
Hopefully shedding some light on #134
=> Improve error messages in pkg/netutils/server/server_test

ovssubnet/api/types.go, ovssubnet/common.go, ovssubnet/registry/registry.go
=> For multitenant plugin, handle both existing and admin namespaces

main.go, ovssubnet/common.go, ovssubnet/controller/kube/bin/openshift-sdn-kube-subnet-setup.sh, ovssubnet/controller/kube/kube.go, ovssubnet/controller/lbr/bin/openshift-sdn-simple-setup-node.sh, ovssubnet/controller/lbr/lbr.go, ovssubnet/controller/multitenant/bin/openshift-sdn-multitenant-setup.sh, ovssubnet/controller/multitenant/multitenant.go
=> Make SDN MTU configurable

ovssubnet/common.go
We will reuse this method in origin osdn api.
=> Expose method for getting node IP

pkg/ovssubnet/api/types.go, pkg/ovssubnet/common.go, pkg/ovssubnet/controller/kube/bin/openshift-ovs-subnet, pkg/ovssubnet/controller/kube/bin/openshift-sdn-kube-subnet-setup.sh, pkg/ovssubnet/controller/kube/kube.go, pkg/ovssubnet/controller/multitenant/bin/openshift-sdn-multitenant-setup.sh, pkg/ovssubnet/controller/multitenant/multitenant.go, plugins/osdn/flatsdn/flatsdn.go, plugins/osdn/multitenant/multitenant.go, plugins/osdn/osdn.go
I always get confused about which variables have plain IP addresses and which ones have IP/mask strings...
=> code cleanup (no substantive changes)

plugins/osdn/flatsdn/flatsdn.go, plugins/osdn/multitenant/multitenant.go
Fix for https://github.com/openshift/origin/issues/4818
Please also refer to https://github.com/openshift/origin/pull/1597
=> Replace hostname -f with unmae -n

plugins/osdn/osdn.go
We don't need to track services per-namespace; we can just use the namespace kapi.NamespaceAll (aka ""), like "oc get --all-namespaces" does.
Closes #158
@pravisankar
=> Simplify service tracking by using kapi.NamespaceAll

hack/debug.sh
We weren't outputting any service-related data. This adds "oc get service" output, and also does pod-to-service connectivity checks (which required streamlining the pod-to-pod connectivity code to avoid having way too much cut+paste).
=> debug.sh improvements

hack/debug.sh
- Parse output of 'host' correctly when /etc/hosts is empty
- Handle the master being a node
- Bail out sooner in case of some errors
- Use $HOME/.kube/config as default KUBECONFIG value
These make it work better/at all with the default OSE config
=> Misc debug.sh fixes

pkg/ovssubnet/controller/multitenant/multitenant.go
del-flows doesn't take all the same arguments add-flow does
pointed out in https://bugzilla.redhat.com/show_bug.cgi?id=1272295
=> Fix cleanup of service OpenFlow rules

pkg/ovssubnet/controller/kube/bin/openshift-sdn-kube-subnet-setup.sh, pkg/ovssubnet/controller/multitenant/bin/openshift-sdn-multitenant-setup.sh
=> Remove redundant tun0 route

pkg/ovssubnet/common.go, plugins/osdn/osdn.go
=> Validate SDN cluster/service network

hack/debug.sh
Resolves a bunch of problems I've seen in the last week. In particular, the "try to find node config file from 'ps' output" commit is needed to make debug.sh work in our ansible OSE installs.
=> debug.sh fixes

pkg/ovssubnet/common.go
Fix related to https://bugzilla.redhat.com/show_bug.cgi?id=1194467
=> Don't loop forever if subnet not found for the node

hack/debug.sh
- Got the 'oc routes' output
- Supressed the host check in ssh
- Unified common code between host and node
- Cleaned up the formatting to make the commands being run a little more obvious
=> Made a few small changes

plugins/osdn/factory/factory.go
Fixes: df2419231f5ad7efea1028cea1690e729204c378
=> Trivial build fix

plugins/osdn/registry.go
Panic found in http://www.fpaste.org/292728/44802319/
=> osdn: Fix out of range panic

hack/debug.sh
This started because I was going to implement #240, but then the bug I needed that for ended up fixed anyway, so I haven't bothered yet. But here are some cleanups and improvements.
I bet @knobunc wants to review this...
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1265586
=> debug.sh fixups

plugins/osdn/registry.go
@dcbw one missing piece of the puzzle ptal
=> Update to new ListOptions client APIs - missing piece of puzzle

pkg/cmd/admin/network/project_options.go, plugins/osdn/common.go, plugins/osdn/ovs/plugin.go, plugins/osdn/registry.go, plugins/osdn/vnids.go
Changes got made to origin's copy of openshift-sdn but not to openshift-sdn itself
=> Resync from origin for kubernetes rebase

plugins/osdn/ovs/controller.go
We need to set the MTU on vovsbr and vlinuxbr to match the MTU that will be used by docker veths and the OVS bridge.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1302907
=> Set MTU on vovsbr/vlinuxbr

plugins/osdn/ovs/controller.go
Add a rule stamp and check that stamp on startup to see if we have
to recreate the OVS bridge and flow rules.  Should fix ambiguity
in the existing rule checking.
=> Implement better OVS flow rule versioning

plugins/osdn/api/types.go, plugins/osdn/common.go, plugins/osdn/ovs/bin/openshift-sdn-ovs, plugins/osdn/ovs/plugin.go, plugins/osdn/registry.go, plugins/osdn/subnets.go
Use "standard" kubernetes ingress/egress annotations to implement bandwidth shaping via OVS.
=> Implement OVS bandwidth shaping

plugins/osdn/ovs/bin/openshift-sdn-ovs, plugins/osdn/ovs/plugin.go
Fix to #266. Possibly should get into https://github.com/openshift/origin/pull/8109
@dcbw
=> Remove unused MTU stuff from bandwidth code

plugins/osdn/ovs/bin/openshift-sdn-ovs
Fix for https://bugzilla.redhat.com/show_bug.cgi?id=1320430
=> Fix qos check in del_ovs_flows()

plugins/osdn/common.go, plugins/osdn/ovs/controller.go, plugins/osdn/vnids.go
Depends on https://github.com/openshift/openshift-sdn/pull/279
=> Do not throw spurious error msgs in watch network namespaces

hack/debug.sh
It would be helpful to get the arp cache for debugging an issue... so I added to the tarball.
=> Changed the debug script to capture the arp cache

plugins/osdn/common.go, plugins/osdn/ovs/plugin.go, plugins/osdn/subnets.go, plugins/osdn/vnids.go
=> Add more logging, to help debug problems

plugins/osdn/registry.go
There's a cache that tracks which namespace IP addresses belong to.  However, the cache logic was not considering that Failed or Complete pods (i.e. not running) could share an IP address with a Running pod.  so the cache code needed to be changed to only add items to the cache when a pod was Running or Pending.  We also track the pod UID to make sure that when we delete, we are deleting the entry for the pod that was running.  So that if a stopped pod is edited, that entry doesn't end up in the cache.
This is reproducible by setting the networkConfig hostSubnetLength to 3 in the master and node config on your cluster.  Then create two namespaces, ns1 and ns2, a service in ns2 that has a selector that matches both pods then create a pod that fails in one (have it run "sleep 5; false", and …
=> Fixes the ip address to namespace cache when pods reuse addresses

plugins/osdn/common.go, plugins/osdn/ovs/plugin.go, plugins/osdn/vnids.go
Fix for bug# https://bugzilla.redhat.com/show_bug.cgi?id=1323279
=> Synchronize and controlled access to vnid map

plugins/osdn/common.go, plugins/osdn/ovs/controller.go, plugins/osdn/registry.go, plugins/osdn/subnets.go, plugins/osdn/vnids.go
Depends on https://github.com/openshift/openshift-sdn/pull/293
=> Make SDN watch resources more resilient

plugins/osdn/common.go
ought to fix https://bugzilla.redhat.com/show_bug.cgi?id=1320959
=> Ignore malformed IP in Node object

hack/debug.sh
Added the output from tc sub-commands to the output so we can see the traffic shaper state.
=> Add tc state to the debug tar

plugins/osdn/ovs/proxy.go, plugins/osdn/registry.go, plugins/osdn/subnets.go, plugins/osdn/vnids.go
closes: https://github.com/openshift/openshift-sdn/issues/307
=> Update subnet when host IP changes instead of delete-old + create-new subnet

plugins/osdn/common.go, plugins/osdn/ovs/proxy.go, plugins/osdn/registry.go, plugins/osdn/subnets.go
Precursor for storing/fetching plugin name from ClusterNetwork.
=> Simplify caching and fetching network information

plugins/osdn/ovs/controller.go, plugins/osdn/ovs/plugin.go
Extracted from https://github.com/openshift/origin/pull/8856
=> Adjust types for rebase, add stub Status method

hack/ipf-debug.sh
As an OpenShift administrator, I want to know when my ipfailover is
causing my network problems.
Extend the nework debug script so that it can determine why keepalived
is not serving an address appropriately. Ideally we work out which
machine the address should be assigned to, then check that only that
machine has the address assigned, and (ideally) ping the address from
other machines to ensure connectivity.
Trello card:
https://trello.com/c/yFco7WvY/268-5-ip-failover-diagnostic-script-demo-supportability-p3-5
Signed-off-by: Phil Cameron pcameron@redhat.com
=> IP Failover diagnostic script

hack/debug.sh
Fix debug.sh error when it is executed on containerized cluster (issue #326)
=> Fix debug.sh error when it is executed on containerized cluster
