openshift/openshift-sdn

openshift-sdn.spec

Only openshift-sdn-node requires the overlay networking components.

openshift-sdn does not require openvswitch or bridge-utils

---

main.go

`newSubnetRegistry()`: Pass `opts.etcdPath` and the subdirectory name (either "subnets" or "minions") to `path.Join` as separate arguments rather than catenating them as strings and passing the catenated string to `path.Join`.
Before this change, if `-etcd-path` were passed a pathname "/foo" that did not end with a slash, openshift-sdn would use directory names "/foosubnets" and "/foominions" instead of "/foo/subnets" and "/foo/minions".

Always treat -etcd-path as a directory

---

pkg/netutils/ip_allocator.go
pkg/netutils/subnet_allocator.go

I believe these fmt.Println are not necessary. If they are necessary, they should use log.Info or other formal message.

Remove unnecessary print

---

rel-eng/openshift-sdn-master.service
rel-eng/openshift-sdn-node.service

Add `Restart=on-failure` to the unit files for openshift-sdn-master and openshift-sdn-node.

Add Restart=on-failure to unit files

---

ovs-simple/bin/openshift-sdn-simple-setup-node.sh
ovs-simple/controller/controller.go
pkg/netutils/subnet_allocator.go
pkg/registry/registry.go

Use clearer and more consistent formatting for output.
Consistently format error values using `%v` with the error values themselves rather than using `%s` and `err.Error()`.
Indicate that we are printing the container network, local host subnet, and gateway for the latter during initialization of openshift-sdn in node mode rather than cryptically printing IP addresses and CIDR suffixes with no explanation of what they are.
Indicate that we are printing the subnet prefix length during initialization of openshift-sdn in master mode rather than cryptically printing a lone number with no explanation of what it means.

Improve output formatting

---

pkg/registry/registry.go

If we get a `nil` response or a non-`nil` error, then retry the watch. Before this change, in the case of a `nil` response and a non-`nil` error, `WatchMinions` would try to dereference the `nil` response.

WatchMinions: Correctly handle errors

---

rel-eng/openshift-sdn-master.service
rel-eng/openshift-sdn-node.service

This formalizes service startup ordering.
Before/After only affect ordering.
Wants/Requires affects dependencies, wants being a weaker form of Requires that will trigger the dependency to start but will carry on if the dependency fails.
My only concern is that I wonder if we should add Before=docker.service because if we don't and we've run openshift-sdn previously it will have configured docker to use lbr0 which will not exist after a reboot before openshift-sdn has created it.

Make service dependency ordering more strict

---

hack/test.sh
pkg/netutils/server/server.go
pkg/netutils/server/server_test.go

An http REST based IPAM server - basic implementation that serves IPs for now, but meant to serve subnets too.
The test uses the netutils package as an example.
@mrunalp PTAL

netutils server

---

rel-eng/openshift-sdn-master.service
rel-eng/openshift-sdn-node.service

Sorry for the second round of systemd service changes. @sosiouxme and I discussed this a good bit and we've arrived at this pattern of adding WantedBy to the [Install] section being a good way to allow optional dependencies.

Service dependencies round2

---

rel-eng/openshift-sdn-master.service
rel-eng/openshift-sdn-node.service

This will allow rsyslog users to split master and node logs if they
wish to do so.

Add SyslogIdentifier=openshift-sdn-{master,node} respectively

---

main.go
ovssubnet/common.go
pkg/api/types.go
pkg/registry/registry.go

Moved some types/structs from registry/ package to a new api/ package. This will facilitate making registry/ as one of the interface implementations. A pluggable implementation can then, choose a non-etcd based backend as an example.
@mrunalp Review please.

first set of reorg for api-fication of openshift-sdn

---

openshift-sdn.spec

I was getting rpm build failures. Does openshift-ovs-subnet get installed into /bin/openshift-ovs-subnet or to /usr/libexec/kubernetes/kubelet-plugins/net/exec/redhat~openshift-ovs-subnet/openshift-ovs-subnet? I think the former?

specfile fixes

---

ovssubnet/common.go

Do not rely on InitMinions implementation to know if subnets already exist or not.
InitMinions always returns nil error with OpenShift integration e.g.
@mrunalp Review please
Fixes: https://github.com/openshift/origin/issues/2834

Fix origin issue#2834; submit existing subnets as in-use

---

openshift-sdn.spec
ovssubnet/bin/openshift-sdn-kube-subnet-setup.sh
ovssubnet/bin/openshift-sdn-simple-setup-node.sh
rel-eng/docker-sdn-ovs.conf

This moves docker network configuration environment variables to a tmpfs file `/run/openshift-sdn/docker-network` rather than persisting it in `/etc/sysconfig/docker-network` The values are then injected into the docker service by loading that as an optional environment file in a docker.service config file installed by openshift-sdn-node at `/usr/lib/systemd/system/docker.service.d/docker-sdn-ovs.conf`
`/run/openshift-sdn/docker-network` is removed at reboot because it's tmpfs and when openshift-sdn-node service is shut down ensuring that when the sdn isn't running everything works.

Don't persist docker network configuration when the sdn hasn't been started

---

Makefile

@mrunalp make install should match what rpm install does. This change is needed for origin's vagrant setup.

install docker systemd conf file

---

ovssubnet/controller/kube/kube.go
ovssubnet/controller/lbr/lbr.go

Sample output of hex encoding the IP address:
Checksum '192.168.1.4': c0a80104
Checksum '192.168.1.5': c0a80105
Checksum '10.168.1.5': 0aa80105
As long as the IP address of a node is unique (which should always be the case), the cookie will be unique too.
@mrunalp Review please.

fix issue#88 - generate unique cookie based on vtep

---

Makefile

It's called differently and not through the k8s network plugin stuff.

Don't install multitenant plugin for now

---

ovssubnet/controller/multitenant/bin/openshift-ovs-multitenant

vnid=0 can already send to any other pods on the same host or across hosts, but those pods cannot send back to vnid=0 because there is no matching rule in table 5 that allows it.  So add a rule for each vnid=0 pod (currently just the 'default' project) that allows any other pod to send packets back to it.
This makes vnid=0 a special "global" namespace that can talk to any other namespace.  Other vnids still cannot talk to other non-0 vnids however, preserving isolation between projects not named "default".

Allow vnid=x to send to vnid=0 on the same host

---

ovssubnet/controller/multitenant/bin/openshift-sdn-multitenant-setup.sh

Docker-only containers (eg, "docker run foobar") get attached to lbr0, and
their traffic flows from lbr0 -> vlinuxbr -> vovsbr -> br0.  To ensure that
docker-only containers can access the rest of the world through tun0, we
need to pass their traffic along instead of dropping it in table #3:
cookie=0x0, duration=12307.238s, table=0, n_packets=292, n_bytes=23330, actions=learn(table=7,hard_timeout=900,priority=200,NXM_OF_ETH_DST[]=NXM_OF_ETH_SRC[],load:NXM_NX_TUN_IPV4_SRC[]->NXM_NX_TUN_IPV4_DST[],output:NXM_OF_IN_PORT[]),goto_table:1
cookie=0x0, duration=12307.227s, table=1, n_packets=165, n_bytes=13199, actions=goto_table:3
<drop due to no match>
Add a rule allowing traffic from vovsbr to jump from table #3 to table #4,
where it will get directed to the right place (either other pods or …

Let docker-only container global traffic through the vSwitch to tun0

---

ovssubnet/controller/multitenant/bin/openshift-sdn-multitenant-setup.sh

Services need to work across nodes. That means being able to reach a pod (any namespace) from any host. The originating node's OVS rules do not handle a swift exit for return traffic (vnid != 0) meant for tun0 (port 2, IP: subnet_gateway). 
This PR adds a special rule in table 2 (as all input traffic from vxlan port is directed to table 2) to send anything meant for the host/service/tun0 directly out (no need to flood the rest of the ports).
Could have put this rule in table 5 also where all the rest of ports decide on which packet is whose, but why jump an extra table.
Also add priority to rules where the matching criterion can overlap (do not assume insertion order).
@dcbw : Review please. Services from another host didnt work without this and they work with this fix.

make cross node services work

---

ovssubnet/controller/multitenant/bin/openshift-sdn-multitenant-setup.sh
ovssubnet/controller/multitenant/multitenant.go

We don't use custom IPAM with the multitenant plugin so we might as well remove it.
It was left-over from the copy & paste of the ovssubnet plugin to multitenant when
we started development.

Remove some dead code

---

ovssubnet/controller/kube/bin/openshift-ovs-subnet

openshift-ovs-subnet fails on Fedora 22 due to 'ip link show' displaying
interface names with a suffix starting with '@', e.g.
24: vetha06b051@if23: ...
Invoking brctl or ovs-* with the interface 'vetha06b051@if23' fails, and
it is necessary to use the name without the suffix (e.g. 'vetha06b051').

Fix veth lookup for kernels with interface suffixes

---

Makefile
ovssubnet/controller/kube/bin/openshift-sdn-kube-subnet-setup.sh

This change is intended to allow openshift-sdn to work in a docker-in-docker (dind) openshift deployment.  I would appreciate feedback before updating the other setup scripts.  I'm hopeful the change in question could be encapsulated as a bash function for reuse rather than duplicated in all the setup scripts.
To test this change with dind: 
$ git clone https://github.com/marun/origin    
$ cd origin
$ git co -b dind-dev origin/dind-dev
$ git clone https://github.com/marun/openshift-sdn
$ cd openshift-sdn
$ git co -b dind-dev origin/dind-dev
$ cd ..
$ hack/dind/up.sh
$ git clone https://github.com/marun/kubernetes ../kubernetes
$ git co -b e2e-network-isolation origin/e2e-network-isolation
$ pushd ../kubernetes/build
$ ./run.sh hack/build-go.sh
$ popd
$ KUBE_ROOT=../kubernetes …

Add support for docker-in-docker deployment

---

ISOLATION.md
README.md
main.go
ovssubnet/api/types.go
ovssubnet/common.go
ovssubnet/controller/kube/kube.go
ovssubnet/controller/lbr/lbr.go
ovssubnet/controller/multitenant/multitenant.go
ovssubnet/registry/registry.go
rel-eng/openshift-sdn-master.sysconfig
rel-eng/openshift-sdn-node.service
rel-eng/openshift-sdn-node.sysconfig

-  Replace 'minion' with 'node' or 'nodeIP' based on context
-  Pass updated node IP in the NodeEvent to avoid cache/stale lookup by net.LookupIP()
-  In openshift-sdn standalone mode, trigger node event when node ip changes

Update subnet openflow rules in case of host ip change

---

ovssubnet/api/types.go
ovssubnet/common.go
ovssubnet/controller/kube/kube.go
ovssubnet/controller/lbr/lbr.go
ovssubnet/controller/multitenant/bin/openshift-ovs-multitenant
ovssubnet/controller/multitenant/bin/openshift-sdn-multitenant-setup.sh
ovssubnet/controller/multitenant/multitenant.go
ovssubnet/registry/registry.go

This reverts commit 8a58881e3c5d9bf3bc7044b2c1c5a60a1fdafe31, reversing changes made to 1694e9adbaae43a42944de1c5243a12dca46a535.
We're going to need more API additions before integrating this into origin, but this is now blocking the integration of pravisankar/upstream-updatesubnet into origin. So revert it for now.
@pravisankar

Revert "Merge pull request #115 from danwinship/service-isolation"

---

ovssubnet/api/types.go
ovssubnet/common.go
ovssubnet/registry/registry.go

We'll be introducing node object in the next PR,
this will differentiate betweeen node name, node ip and node object.
Sub.Sub is confusing, Subnet is used for referring object and
SubnetIP for the subnetwork IP.

Renamed some field names to remove confusion

---

main.go
ovssubnet/api/types.go
ovssubnet/common.go
ovssubnet/controller/kube/kube.go
ovssubnet/controller/lbr/lbr.go
ovssubnet/controller/multitenant/bin/openshift-ovs-multitenant
ovssubnet/controller/multitenant/bin/openshift-sdn-multitenant-setup.sh
ovssubnet/controller/multitenant/multitenant.go
ovssubnet/registry/registry.go

OK, resubmitting the service isolation stuff. You can diff against danwinship/openshift-sdn service-isolation-old to see what's changed; basically it's just adding the service network to StartMaster and WriteNetworkConfig, which is needed in the origin osdn plugin to get that into the ClusterNetwork.

Multi-tenant service isolation (again!)

---

ovssubnet/api/types.go
ovssubnet/common.go
ovssubnet/registry/registry.go

This will avoid cases where node IP resolution on
master and node differs for various reasons (stale dns cache, etc.)

Get node IP from GetNodes() instead of net.Lookup()

---

ovssubnet/controller/multitenant/bin/openshift-sdn-multitenant-setup.sh

This change updates the multitenant setup script to support
docker-in-docker deployment, which uses supervisord instead of systemd.

Add support for dind in multitenant plugin

---

ovssubnet/controller/kube/bin/openshift-ovs-subnet

Pretty simple. The only trick is that we have to remove the global "set -x" since the exec plugin tries to parse the combined stderr+stdout for the status, so we can't use -x on the status hook.
Closes #142. (The multitenant plugin side is in origin, not openshift-sdn, and will be addressed by https://github.com/openshift/origin/issues/4170.)

Implement kubernetes status hook in kube plugin

---

ovssubnet/controller/kube/kube.go
pkg/netutils/server/server.go
pkg/netutils/server/server_test.go

TestIPServe() was running ListenAndServeNetutilServer() in a goroutine but not necessarily waiting for it to actually start listening. Fix that by having ListenAndServeNetutilServer() first listen and then
spawn a goroutine to serve, and then return, and having TestIPServe() wait for it to return.
Closes #134
(Not that we're actually using this code anyway any more... if we don't expect to use it in the future maybe we should just remove pkg/netutil/server ?)

Fix race condition in pkg/netutils/server/server_test.go

---

ovssubnet/api/types.go
ovssubnet/common.go
ovssubnet/registry/registry.go

Related Issue: #145 
Watch interface for SDN resources takes ready and startVersion channels.
ready channel provides synchronization between watch and get resource
startVersion channel tells watch interface from which resource version to process the changes. Without this channel, watch interface may process the items multiple times and that can have side effects. Example: delete namespace needs deletion of VNID but ignoring if not present in this case may miss genuine error in our code. 
Ignore reviewing  ovssubnet/registry/registry.go (stale code, changes made just to make 'make' happy)

Fix SDN race conditions during master/node setup

---

ovssubnet/controller/kube/bin/openshift-sdn-kube-subnet-setup.sh
ovssubnet/controller/lbr/bin/openshift-sdn-simple-setup-node.sh
ovssubnet/controller/multitenant/bin/openshift-sdn-multitenant-setup.sh

Docker creates docker0 with a 172.16/16 route by default, and does not clean it up on exit.  This interface is not used with OpenShift-SDN and the routing simply conflicts with existing hosts folks may have in this private IP range.
OpenShift-SDN creates a bridge (lbr0) for Docker to use, however it is brought up after the 1st start of the docker service on boot, hence docker0 is always created.  The sequence is as follows (for OpenShift):
- docker service (which ​creates docker0 b.c. lbr0 does not exist yet)
- openshift-node service (with openshift-sdn-ovs linked in)
- starts /usr/bin/openshift-sdn-kube-subnet-setup.sh
- (*) creates /run/openshift-sdn/docker-network with "-b lbr0 ...", and of course lbr0 amongst others
- restarts docker
So it looks like the cleanest place to get rid of …

Cleanup docker0 interface before restarting docker

---

hack/debug.sh

This is still slightly a work in progress, but it's basically working (unless people hate what it does and want a total rewrite...).
This adds a script which you can run on the OpenShift master, which will gather data there, on each node, and in each running pod, which can then be sent to a human for debugging purposes. (Automatically diagnosing problems comes next.) Currently this includes:
- `journalctl --unit openshift-master.service` on the master and `journalctl --unit openshift-node.service` on each node
- `journalctl --boot` on the master and each node. (**FIXME**: too invasive? Might make admins nervous...)
- `ip a` and `ip r` on the master, each node, and inside each pod
- `iptables-save` on the master and each node
- `/etc/hosts` from the master and each node
- `oc get nodes -o …

Add a tool for gathering data to debug networking problems

---

ovssubnet/controller/multitenant/bin/openshift-sdn-multitenant-setup.sh

It's dumb that we use port 9 for vovsbr, and then containers get ports 3-8 and 10+...
Changing this in kube would require an upgrade path, but we don't promise upgradeability with multitenant yet.

Move vovsbr to br0 port 3 rather than 9

---

pkg/ovssubnet/controller/kube/bin/openshift-sdn-kube-subnet-setup.sh
pkg/ovssubnet/controller/multitenant/bin/openshift-sdn-multitenant-setup.sh

The docker-in-docker supervisord setup uses different config files than the systemd setup, but we were deciding whether setup was needed based on whether the systemd files were correct.
@marun

Update setup_required to do the correct check for docker-in-docker

---

pkg/ovssubnet/controller/kube/bin/openshift-ovs-subnet
pkg/ovssubnet/controller/multitenant/bin/openshift-ovs-multitenant

Outputting nothing will lead to the default from 'docker inspect' itself. So avoid multiple pounding of docker daemon with docker inspect calls.

omit reconstructing IP address with docker inspect

---

hack/debug.sh

1. handle naming differences between origin and ose (https://bugzilla.redhat.com/show_bug.cgi?id=1265979)
2. Fix deprecation warnings since the kubernetes rebase
3. Improve an error message

More debug.sh updates

---

pkg/ovssubnet/common.go
pkg/ovssubnet/controller/kube/bin/openshift-sdn-kube-subnet-setup.sh
pkg/ovssubnet/controller/multitenant/multitenant.go

To avoid problems with iptables locking, we need to use the -w flag, if available. Kubernetes's pkg/util/iptables has code to check for its availability and use it if so, so the simplest fix is to just switch to using that.
(Closes https://bugzilla.redhat.com/show_bug.cgi?id=1267670)

Use iptables -w flag

---

pkg/cmd/admin/network/isolate_projects.go
pkg/cmd/admin/network/join_projects.go
pkg/cmd/admin/network/pod_network.go
pkg/cmd/admin/network/project_options.go
pkg/cmd/admin/network/unisolate_projects.go
pkg/ovssubnet/api/types.go
pkg/ovssubnet/common.go
pkg/ovssubnet/controller/kube/bin/openshift-ovs-subnet
pkg/ovssubnet/controller/kube/kube.go
pkg/ovssubnet/controller/multitenant/bin/openshift-ovs-multitenant
pkg/ovssubnet/controller/multitenant/multitenant.go
plugins/osdn/multitenant/plugins.go
plugins/osdn/osdn.go

- Join project networks:
* oadm pod-network join-projects --to=[project-name] [list of projects] | --selector=[project-labels]
- Unisolate project networks:
* oadm pod-network unisolate-projects [list of projects] | --selector=[project-labels]
- Isolate project networks: 
* TBD (some preliminary work done)
- Persist Net namespaces with VNID=0
- Release VNID only if no namespace is using it
- openshift network plugins can handle non pod infra container
- openshift-ovs-multitenant/openshift-ovs-subnet cleanup

Admin command to manage project network

---

pkg/ovssubnet/api/types.go
pkg/ovssubnet/common.go
plugins/osdn/flatsdn/flatsdn.go
plugins/osdn/multitenant/multitenant.go
plugins/osdn/osdn.go

Problem: because we only handle service isolation on the source end, you can work around isolation (of both pods and services) by creating a headless service and then manually assigning it endpoints in another project
Solution 1: Use pure-iptables-based service proxying, then do isolation at the destination rather than the source. But this turns out to not work because we still have to masquerade the packets (or else the service will try to send its response directly back to the client, which will reject them because it doesn't have an open connection to the service pod IP) so the destination doesn't know the source IP.
Solution 2: Use OVS-based service proxying instead of iptables so we can carry the source VNID through the whole process. But we still need to masquerade, for the same …

Service endpoint isolation

---

pkg/ovssubnet/controller/kube/bin/openshift-sdn-kube-subnet-setup.sh
pkg/ovssubnet/controller/multitenant/bin/openshift-sdn-multitenant-setup.sh

This will eliminate migration script.

Detect SDN setup requirement when user switches between flat and multitenant plugins

---

pkg/ovssubnet/controller/kube/bin/openshift-ovs-subnet

The non-multitenant plugin got broken as part of the changes that went with the new oadm commands. The multitenant plugin still worked fine so none of us noticed... Gotta get those automated tests working...
Fixes https://github.com/openshift/origin/issues/5152
cc @pravisankar @sdodson

Fix non-multitenant pod routing

---

pkg/ovssubnet/controller/kube/bin/openshift-ovs-subnet
pkg/ovssubnet/controller/multitenant/bin/openshift-ovs-multitenant

OpenFlow rules were getting left behind because the TearDown was erroring out early because it was trying to remove the veth from the bridge after the veth had already been destroyed.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1272295
@pravisankar

Clean up stale OVS flows correctly / don't error out of TearDown early

---

pkg/ovssubnet/controller/multitenant/bin/openshift-ovs-multitenant

Kubernetes now seems to destroy the veths before running Teardown, so it's no longer possible to find the OVS port a container was attached to, so we have to use different logic to clean up after them.
(Last time I stupidly tested against the kube plugin so didn't notice I hadn't fully fixed the multitenant plugin...)
@pravisankar

Fix multitenant flow cleanup again

---

pkg/ovssubnet/controller/kube/bin/openshift-sdn-kube-subnet-setup.sh
pkg/ovssubnet/controller/multitenant/bin/openshift-sdn-multitenant-setup.sh

docker-in-docker cluster deployment is now managed by systemd, so
supporting supervisord when running in a container is no longer necessary.

Remove support for supervisord-managed docker

---

pkg/ovssubnet/controller/multitenant/bin/openshift-sdn-multitenant-setup.sh

We had the rules for "all pods can connect to VNID 0 services", but not for "VNID 0 pods can connect to all services".
Closes https://bugzilla.redhat.com/show_bug.cgi?id=1275953

Allow traffic from VNID 0 pods to all services

---

pkg/ovssubnet/api/types.go
pkg/ovssubnet/common.go
plugins/osdn/osdn.go

Closes https://bugzilla.redhat.com/show_bug.cgi?id=1275954
One problem; it appears that any time any service changes, we get a modify for *every* service! But modifying services should be rare-ish, so I'd say go with this for 3.1.0 and we can add diffing to get the minimal set of deletes+adds for 3.1.1.
@pravisankar @dcbw

Track changes to services

---

hack/debug.sh

See https://bugzilla.redhat.com/show_bug.cgi?id=1274591#c5
The errors here make me realize that we're operating on potentially-untrusted user-generated data from within a shell script that needs to be run as root... We're going to need to fix that. Until then, we should remember that the script is not safe for OpenShift users who don't trust all of their own users.

debug.sh: fix handling of pods with no ip

---

pkg/ovssubnet/controller/kube/bin/openshift-sdn-kube-subnet-setup.sh
pkg/ovssubnet/controller/multitenant/bin/openshift-sdn-multitenant-setup.sh

For use in an origin-node image that's built atop openshift/origin. The systemd service that starts the node container is Restart=always and is responsible for starting the node again after docker has been restarted.

Isolate docker bridge initialization to enable containerized installs

---

Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/errors/errors.go

openshift-sdn's (minimal) tests fail now because pkg/netutils/common.go now requires kubernetes's pkg/util/errors. So this just copies that into Godeps. I didn't bother trying to do it "properly". Maybe we should just rm Godeps/Godeps.json and Godeps/Readme?
@pravisankar

Fix netutils tests

---

plugins/osdn/multitenant/plugins.go

The script doesn't care about the VNID, so we shouldn't bother
looking it up only to fail if the teardown request comes after
the master has sent the NetNamespace deleted notification.
https://bugzilla.redhat.com/show_bug.cgi?id=1277383

Remove unused lookup of VNID for TearDownPod

---

plugins/osdn/api/types.go
plugins/osdn/common.go
plugins/osdn/factory/factory.go
plugins/osdn/flatsdn/flatsdn.go
plugins/osdn/multitenant/multitenant.go

See https://github.com/openshift/origin/pull/5840 (specifically https://github.com/openshift/origin/pull/5840/files#r44958452). We need to return the FilteringEndpointsConfigHandler sooner, so that StartNode() can be called as a goroutine, because StartNode() can't return until after its caller does, because of the weird way startup is currently organized.
(origin side is https://github.com/danwinship/origin/tree/osdn-update)
@dcbw

Shuffle things around in node start to fix a hang

---

plugins/osdn/factory/factory.go

We need to silently accept unknown plugins in origin, so if we don't know about it, don't return an error that Origin will exit on.

Don't return an error if the plugin is unknown

---

plugins/osdn/ovs/bin/openshift-sdn-ovs
plugins/osdn/ovs/bin/openshift-sdn-ovs-setup.sh
plugins/osdn/ovs/controller.go

I'm still working out how to test this, but (a) it doesn't break things it's not supposed to break, and (b) ovs-appctl ofproto/trace shows it working.
Rather than adding rules to subnet and multitenant separately, I just switched subnet over to using the multitenant rules (with one short-circuit around service isolation). Testing consistently shows that the multitenant rules are faster anyway, and this also pulls in one other security fix (making it so that containers can only send packets with their own IP address as source; previously multitenant enforced that but subnet did not).

VXLAN filtering

---

plugins/osdn/api/types.go
plugins/osdn/factory/factory.go
plugins/osdn/ovs/plugin.go

It's currently osdn specific anyway, plus we need it here to avoid
an import loop once some of liggitt's suggestions are taken for
origin SDN initialization ordering.

Move FilteringEndpointsConfigHandler into openshift-sdn

---

plugins/osdn/subnets.go

The node subnet wait is run from a goroutine and will run
concurrently with the rest of kubelet setup.  But when a node
is heavily loaded kubelet setup might actually take close to
10 seconds or more before registration with the master starts.
That causes the subnet wait to time waiting for the subnet
registration which hasn't happened yet.  Bump the timeout.
https://bugzilla.redhat.com/show_bug.cgi?id=1290967

Bump node subnet wait to 30 seconds (from 10)

---

plugins/osdn/registry.go

Split out of #227. This is the openshift-sdn side of https://github.com/openshift/origin/pull/6349.

Don't redundantly validate the ClusterNetwork

---

pkg/cmd/admin/network/isolate_projects.go
pkg/cmd/admin/network/join_projects.go
pkg/cmd/admin/network/make_projects_global.go

Admin commands are client centric, and should not take dependencies on
plugin implementations (which brings in lots of undesirable packages).
This change will enable the admin part of the origin CLI to be embedded
into oc.

Admin commands should not depend on OVS code

---

pkg/ipcmd/ipcmd.go
pkg/ipcmd/ipcmd_test.go
pkg/ovs/ovs.go
pkg/ovs/ovs_test.go

Fixes the breakage seen in https://github.com/openshift/origin/pull/6532
The openshift binary gets run as part of the tests/CI, so we can't panic if OVS is missing. But just returning an error will still cause it to exit at startup time when running normally, so that's OK. (And
it looks like nothing else caches the result of LookPath(), so we won't either; this is necessary to make it possible to test the missing-command codepaths.)
@dcbw

Make pkg/ipcmd and pkg/ovs not panic if their binaries are missing

---

plugins/osdn/ovs/controller.go

A reorganization of the rules in the danw/vxlan-filtering merge broke node -> remote-pod traffic (and also vnid-0-pod -> remote-pod traffic), which among other things meant that remote services would no longer work when referred to by service IP.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1293251
Probably also https://github.com/openshift/openshift-sdn/issues/231 and https://github.com/openshift/origin/issues/5796.

Fix a bug with services in multitenant

---

plugins/osdn/ovs/bin/openshift-sdn-ovs

Closes https://bugzilla.redhat.com/show_bug.cgi?id=1293759

Add a missing 'ovs-ofctl del-flows' on pod teardown

---

plugins/osdn/ovs/controller.go

(This was broken by the switch to iptables-based services, because the request would use the default IP rather than the tun0 IP, and then the response would come back via the wrong path and not get un-NAT-ed.)
Closes #232 
@dcbw: maybe get this into the resync too?

Add a route to fix up service IP usage from the node.

---

pkg/netutils/subnet_allocator.go
pkg/netutils/subnet_allocator_test.go

Given ClusterNetworkCIDR "10.1.0.0/16" and HostSubnetLength 7, the current git master algorithm would allocate subnets in the order:
- 10.1.0.0/25
- 10.1.0.128/25
- 10.1.1.0/25
- 10.1.1.128/25
and then when you see a pod IP like "10.1.0.130", you have to stop and think to figure out which node it's on. Lame!
This branch fixes it so that the allocation order becomes:
- 10.1.0.0/25
- 10.1.1.0/25
- 10.1.2.0/25
- ...
- 10.1.255.0/25
- 10.1.0.128/25
- 10.1.1.128/25
- 10.1.2.128/25
- ...
meaning that if you have fewer than 256 nodes, then every node will have a unique 3rd octet, just like with the HostSubnetLength=8 case.
Oh, and then there's also a mostly-unrelated change to registry.go that removes the redundant validation of ClusterNetwork changes so that …

Subnet allocation fixes

---

plugins/osdn/ovs/controller.go

I don't know whether that's correct, but I figure that bridge-nf-call is a typo. I did not have a kernel in reach that had _that_ sysctl. When using net.bridge.bridge-nf-call-iptables, container egress works alright.
Note, that I did not get into the trouble to verify that change by building a new openshift/node image.

use net.bridge.bridge-nf-call-iptables sysctl key

---

plugins/osdn/registry.go

Prevents https://bugzilla.redhat.com/show_bug.cgi?id=1298942. Not exactly sure why there is an invalid endpoint, but apparently it only happens while something is being restarted. Anyway, the log message may help figure out what's actually happening.

Don't crash on endpoints with invalid/empty IP addresses

---

plugins/osdn/factory/factory.go
plugins/osdn/registry.go

This reverts #247 as it turns out that it wasn't actually "IP" that was nil there, it was registry.serviceNetwork.
This new version requires origin changes too, because when creating the plugin, we now need to know whether we're the master or a node.
Not tested yet, so don't merge it. Waiting to hear from Jeremy on https://bugzilla.redhat.com/show_bug.cgi?id=1298942

Crash in the right place if the ClusterNetwork record can't be read

---

plugins/osdn/factory/factory.go
plugins/osdn/registry.go

Already tested in origin; jenkins and travis pass.
The origin node startup code calls `StartSDN()` followed by `StartProxy()`. `StartSDN()` calls `oc.StartNode()`, which depends on `ClusterNetwork.Get("default")` returning non-nil (via `registry.GetClusterNetworkCIDR()`), so when `StartProxy()` calls `SetBaseEndpointsHandler()`, we know it will succeed.
(Note that most of this patch is just reverting #248.)
@dcbw PTAL

endpoints nil crash fix (this time for sure!)

---

plugins/osdn/ovs/controller.go

This ended up in the wrong place after one of the rewrites/rebases. We should check if everything is already set up correctly *before* forcibly recreating lbr0.
This didn't matter until #249 landed, because alreadySetUp() was always returning false. But now, if nothing has changed; lbr0 gets recreated, but then alreadySetUp() returns true before we re-add vlinuxbr to it, so non-OpenShift containers would be broken.
@dcbw PTAL

Put the network-already-set-up check in the right place

---

plugins/osdn/ovs/bin/openshift-sdn-ovs
plugins/osdn/subnets.go

This (a) improves the plugin script's "UpdatePod" behavior, and (b) calls UpdatePod on every currently-running pod at startup. Which means:
- If br0 was destroyed and recreated, pods will now correctly get reattached (https://bugzilla.redhat.com/show_bug.cgi?id=1299756)
- If ClusterNetworkCIDR changed, pods will get the updated local route (https://github.com/openshift/openshift-sdn/issues/239)

Fix up pod network connectivity at startup

---

plugins/osdn/common.go
plugins/osdn/ovs/plugin.go
plugins/osdn/subnets.go
plugins/osdn/vnids.go

When using multi-tenant, we need to run VnidStartNode() before updating the pods, to ensure that VNIDMap is initialized. But VnidStartNode() assumes that SubnetStartNode() has already run. So,
move the pod-updating code out of SubnetStartNode() into PluginStartNode().

Re-fix reconnect-pods-on-restart code

---

plugins/osdn/ovs/bin/openshift-sdn-ovs
plugins/osdn/ovs/controller.go
plugins/osdn/ovs/plugin.go

It turns out we should never have switched to using "learn" rather than hardcoding all the mappings, because learning can only work correctly if you're willing to flood packets when you don't have a mapping. We do this for ARP packets, but not for IP packets, because that could violate isolation. But this means that if our mapping times out before a container ARP cache does, then we'll stop being able to deliver their packets. (This won't happen if the two machines are in regular communication, because OVS will keep bumping up the timeout in that case. It only happens if they talk, and then a long period of time goes by with no communication [but not *too* long], and then they try to talk again.)
Also adds some more sanity-checking to the rules to prevent spoofed packets.
Closes #231 …

OVS rule updates for ARP bugs, etc

---

plugins/osdn/ovs/bin/openshift-sdn-ovs
plugins/osdn/ovs/controller.go

Fixes to arp-fixes based on the testing done in https://bugzilla.redhat.com/show_bug.cgi?id=1311702:
- Add a missing del-flows for new ARP flows on pod deletion.
- Remove the newly-added anti-spoofing checks for tun0 traffic, which break in the face of service-related masquerading.
- Fix the handling of VNID 0 service flows: we need to create the rules for them, just without a reg0 check.

Fixes to danwinship/arp-fixes

---

plugins/osdn/common.go
plugins/osdn/ovs/plugin.go
plugins/osdn/registry.go
plugins/osdn/subnets.go

If a HostSubnet is edited or the node's IP address is changed such
that the NodeIP is contained within its own SubnetCIDR, a routing loop
will be created in the OVS bridge and cause a kernel panic by
exhausing kernel stack space.
Prevent the cluster from starting when this happens by ensuring that
the NodeIP is not contained within the cluster network CIDR.
https://bugzilla.redhat.com/show_bug.cgi?id=1295486

Ensure NodeIP doesn't overlap with the cluster network

---

hack/debug.sh

This changes the debug script to call systemctl to get the complete docker unit file and then finds out the docker run file used, and pulls the contents of that to get the interface config.

Improved the debug script to grab the docker unit file.

---

plugins/osdn/api/types.go
plugins/osdn/common.go
plugins/osdn/ovs/controller.go
plugins/osdn/ovs/plugin.go
plugins/osdn/registry.go
plugins/osdn/subnets.go
plugins/osdn/vnids.go

The individual commit messages mostly explain the changes here...
The change to get rid of the wrapper types was inspired by the egress router work: I wanted to be able to check the pod's SecurityContext from plugin.go, which would have required copying that info from kapi.Pod to osdnapi.Pod, much as dcbw had just done for annotations... but that seemed silly when we could just use the kapi.Pod directly instead.

plugin refactoring/cleanup

---

plugins/osdn/ovs/bin/openshift-sdn-ovs
plugins/osdn/ovs/plugin.go

This builds on the refactoring in #270; only the final commit ("Implement "openshift.io/macvlan" annotation on pods") is new
With this addition, you can run https://github.com/danwinship/egress-router, and this should be considered in that context.
We had talked before about whether implementing egress IPs as a pod made sense, and I eventually decided that it does:
- It provides an obvious way to enable/disable the service.
- It keeps the logic outside of openshift-sdn/origin, so we can deprecate/replace it later if we need to.
- You can point a service at the pod and then other pods refer to it by that and don't need to know the details of where it's running.
- You can use a nodeSelector on the pod to force it to only be deployed to nodes that are capable of using the egress IP.
- If the …

Add annotation for adding macvlan interface to pod (for egress-router)

---

hack/debug.sh

It would have been handy to see the docker state vs. the openshift state for containers for a bug I was working on.  This addresses that deficiency.

Added 'docker ps -a' to the node debug items

---

plugins/osdn/ovs/bin/openshift-sdn-ovs

del_ovs_flows() uses ovs port to fetch qos record,
so delete ovs port in the end.
Bug fix for https://bugzilla.redhat.com/show_bug.cgi?id=1322077

Fix network pod teardown

---

plugins/osdn/common.go
plugins/osdn/ovs/controller.go
plugins/osdn/vnids.go

- Don't perform AddServiceRules with global/zero vnid when the vnid is not found in the VNIDMap
- We don't need to pass vnid for DeleteServiceRules

Fix watch services for multitenant plugin

---

plugins/osdn/common.go
plugins/osdn/registry.go
plugins/osdn/subnets.go
plugins/osdn/vnids.go

Trello card: https://trello.com/c/hB3SyOLw
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1275904

Fix SDN get and watch resource workflow

---

plugins/osdn/ovs/controller.go

The rest of the ovs sdn rules had removed them in other patches.  This catches the other cases we hadn't yet changed.

Removed the cookies from the remote node rules.

---

plugins/osdn/registry.go

The pod-monitoring and endpoint-filtering threads might both run at the same time so we need a mutex here. Fixes #291.
As for the actual race condition, if a pod which is an endpoint is added, and OnEndpointsUpdate() ends up running before trackPod(), then the pod won't be allowed as an endpoint and will be ignored until the
next time OnEndpointsUpdate() runs, when it will get picked up. So isolation is guaranteed but correct functioning of the service is not...
But can that actually happen? It seems unlikely unless there's really unfair thread scheduling... (The more common case is that trackPod/unTrackPod and OnEndpointsUpdates are running at the same time for unrelated reasons.) Anyway, we don't like this code and want it to go away and be replaced by something else anyway... …

Add a mutex to registry.podsByIP

---

plugins/osdn/ovs/plugin.go

Return better errors from SetUpPod/TearDownPod

---

hack/debug.sh

Our OpenFlow rules now try to prevent vxlan spoofing, but the test packet traces in debug.sh didn't get updated for that, so they're now seen as being spoofed and get dropped when they shouldn't
(also another minor fix for dind cluster support)

debug.sh fixes for vxlan anti-spoofing

---

plugins/osdn/common.go
plugins/osdn/ovs/controller.go
plugins/osdn/registry.go
plugins/osdn/subnets.go

We don't expect nodes to be added/removed very often so the log
spam won't be large.

Add more HostSubnet logging

---

pkg/cmd/admin/network/project_options.go
plugins/osdn/ovs/plugin.go

Also adds the SHAPING capability to the plugin quiet the kubernetes
warning when shaping annotations are present and openshift-sdn handles
them.

Update for origin kubernetes rebase

---

plugins/osdn/factory/factory.go
plugins/osdn/ovs/controller.go
plugins/osdn/ovs/plugin.go

Remove unused GetName() from ovs controller and we already have
Name() to return the name of the sdn plugin if needed.

Refer SDN plugin names and annotations by constants

---

plugins/osdn/api/types.go
plugins/osdn/factory/factory.go
plugins/osdn/ovs/plugin.go
plugins/osdn/ovs/proxy.go
plugins/osdn/registry.go
plugins/osdn/vnids.go

With more origin code this should give us the ability to run the proxy in a separate process.
I chose to keep the registry since the proxy also needs the origin client to get the ClusterNetwork, but I could split that out and simplify things a but further if anyone wants?

Split proxy endpoint filtering out into separate object

---

pkg/cmd/admin/network/isolate_projects.go
pkg/cmd/admin/network/join_projects.go
pkg/cmd/admin/network/make_projects_global.go

Following the upstream style changes from Kubernetes and OpenShift
Origin.
See https://github.com/openshift/origin/pull/8454.

Remove prompts from commented examples

---

plugins/osdn/ovs/bin/openshift-sdn-ovs
plugins/osdn/ovs/plugin.go

If we fail to get info from docker/ip/etc, fail immediately rather than failing with a syntax error due to substituting in an empty value later.
inspired by https://bugzilla.redhat.com/show_bug.cgi?id=1333393, though as noted there, we probably want a better solution eventually to ensure we don't leave cruft in OVS

Fail more cleanly on script errors

---

hack/sync-to-origin.sh

I don't know if it's go's fault or godep or our Makefiles or what, but something isn't very good about noticing that Godeps/_workspace/src/github.com/openshift/openshift-sdn/ has changed, so I tend to have to "make clean; make" after doing a sync-to-origin. This patch "fixes" things by deleting the openshift-sdn .a files after a sync so that the next origin make will have to rebuild them. (I thought about trying to make this a bit more clever about which .a files it deletes, but openshift-sdn is small enough that it doesn't take that much time to rebuild all of it anyway...)

Force a rebuild after ./hack/sync-to-origin.sh

---

hack/debug.sh

This will also handle the case where optional config options are used before --config
Example: /usr/bin/openshift start node --loglevel=5 --config=/...

debug.sh: Fix fetching config file for service

---

plugins/osdn/common.go
plugins/osdn/factory/factory.go
plugins/osdn/ovs/plugin.go
plugins/osdn/registry.go
plugins/osdn/subnets.go

Depends on https://github.com/openshift/openshift-sdn/pull/317
Trello card: https://trello.com/c/Lr0wa4hr/228-3-detect-master-and-node-sdn-plugin-mismatch-sdn

Persist network plugin name as part of cluster network creation

---

hack/debug.sh

When the /etc/hosts has extra spaces in the end of the line or the
node name is not the last token in the line the node is not discovered
and the result is error messages in the report.
This is fixed by using "getent ahostsv4" to look for the host name.
Fixes: 1328009
Signed-off-by: Phil Cameron <pcameron@redhat.com>

debug.sh will report incorrect message

---

hack/debug.sh

It can be helpful when debugging arp problems to get the neighbor
cache stats.

Change the way we get the neigbor cache to include stats

---

hack/debug.sh

With the change to CNI the loop that pulled the envfile was consuming all of the other nodes... so the loop ended.  This checks that a file is present before calling cat.

Correct the code that pulls the docker envfile

---

hack/debug.sh

Since some cloud services (especially EC2) disables ICMP by default,
debug.sh outputs the ping failure. Although users can workaround it by
setting security group, they would like to avoid such a workaround.
This patch changes node connectivity check to use curl instead of ping.

debug.sh: replace ping to curl

---

hack/debug.sh

Although atomic-openshift-master RPM package includes
`/usr/lib/systemd/system/atomic-openshift-master.service`, latest ansible
installer removes the file if installed with master HA configuration.
Please refer to
~~~
[root@knakayam-ose37-master1 ~]# rpm -qf /usr/lib/systemd/system/atomic-openshift-master.service
atomic-openshift-master-3.7.9-1.git.0.7c71a2d.el7.x86_64
[root@knakayam-ose37-master1 ~]# ls /usr/lib/systemd/system/atomic-openshift-master.service
ls: cannot access /usr/lib/systemd/system/atomic-openshift-master.service: No such file or directory
~~~
So, this patch changes script to continue to run if not only
`atomic-openshift-master.service` but also
`atomic-openshift-master-controllers.service` exists.

debug.sh: continue to run script if controllers path exists

---

hack/debug.sh

We weren't copying meta from a remote master so it didn't work in that case when it tried to read the nodelist.

Fixed the bastion host case so meta is also copied from the master
